create database e-lab

CREATE TABLE IF NOT EXISTS `players` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `vardas` varchar(255) NOT NULL,
  `pavarde` varchar(255) NOT NULL,
  `automobilio_nr` varchar(6) NOT NULL,
  `telefono_nr` int(15) NOT NULL,
  `email` varchar(100) NOT NULL,
  `miestas` varchar(50) NOT NULL,
  `registracijos_data` date NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE admin
(
id int(11) not NULL AUTO_INCREMENT,
username VARCHAR(30) NOT NULL,
password VARCHAR(30) NOT NULL,
PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE `players` ADD UNIQUE( `automobilio_nr`, `telefono_nr`, `email`) 

INSERT INTO admin (username, password)
VALUES
(
'admin', 'admin'
)

CREATE TABLE miestai
(
miestai VARCHAR(255) NOT NULL
)

INSERT INTO miestai (miestai)
VALUES
('Akmenė, Lietuva'),
('Alytus, Lietuva'),
('Anykščiai, Lietuva'),
('Ariogala, Lietuva'),
('Baltoji Vokė, Lietuva'),
('Birštonas, Lietuva'),
('Biržai, Lietuva'),
('Daugai, Lietuva'),
('Druskininkai, Lietuva'),
('Dūkštas, Lietuva'),
('Dusetos, Lietuva'),
('Eišiškės, Lietuva'),
('Elektrėnai, Lietuva'),
('Ežerėlis, Lietuva'),
('Gargždai, Lietuva'),
('Garliava, Lietuva'),
('Gelgaudiškis, Lietuva'),
('Grigiškės, Lietuva'),
('Ignalina, Lietuva'),
('Jieznas, Lietuva'),
('Jonava, Lietuva'),
('Joniškėlis, Lietuva'),
('Joniškis, Lietuva'),
('Jurbarkas, Lietuva'),
('Kaišiadorys, Lietuva'),
('Kalvarija, Lietuva'),
('Kaunas, Lietuva'),
('Kavarskas, Lietuva'),
('Kazlų Rūda, Lietuva'),
('Kėdainiai, Lietuva'),
('Kelmė, Lietuva'),
('Kybartai, Lietuva'),
('Klaipėda, Lietuva'),
('Kretinga, Lietuva'),
('Kudirkos Naumiestis, Lietuva'),
('Kupiškis, Lietuva'),
('Kuršėnai, Lietuva'),
('Lazdijai, Lietuva'),
('Lentvaris, Lietuva'),
('Linkuva, Lietuva'),
('Marijampolė, Lietuva'),
('Mažeikiai, Lietuva'),
('Molėtai, Lietuva'),
('Naujoji Akmenė, Lietuva'),
('Nemenčinė, Lietuva'),
('Neringa, Lietuva'),
('Nida, Lietuva'),
('Obeliai, Lietuva'),
('Pabradė, Lietuva'),
('Pagėgiai, Lietuva'),
('Pakruojis, Lietuva'),
('Palanga, Lietuva'),
('Pandėlys, Lietuva'),
('Panemunė, Lietuva'),
('Panevėžys, Lietuva'),
('Pasvalys, Lietuva'),
('Plungė, Lietuva'),
('Priekulė, Lietuva'),
('Prienai, Lietuva'),
('Radviliškis, Lietuva'),
('Ramygala, Lietuva'),
('Raseiniai, Lietuva'),
('Rietavas, Lietuva'),
('Rokiškis, Lietuva'),
('Rūdiškės, Lietuva'),
('Salantai, Lietuva'),
('Seda, Lietuva'),
('Simnas, Lietuva'),
('Skaudvilė, Lietuva'),
('Skuodas, Lietuva'),
('Smalininkai, Lietuva'),
('Subačius, Lietuva'),
('Šakiai, Lietuva'),
('Šalčininkai, Lietuva'),
('Šeduva, Lietuva'),
('Šiauliai, Lietuva'),
('Šilalė, Lietuva'),
('Šilutė, Lietuva'),
('Širvintos, Lietuva'),
('Švenčionėliai, Lietuva'),
('Švenčionys, Lietuva'),
('Tauragė, Lietuva'),
('Telšiai, Lietuva'),
('Tytuvėnai, Lietuva'),
('Trakai, Lietuva'),
('Troškūnai, Lietuva'),
('Ukmergė, Lietuva'),
('Utena, Lietuva'),
('Užventis, Lietuva'),
('Vabalninkas, Lietuva'),
('Varėna, Lietuva'),
('Varniai, Lietuva'),
('Veisiejai, Lietuva'),
('Venta, Lietuva'),
('Viekšniai, Lietuva'),
('Vievis, Lietuva'),
('Vilkaviškis, Lietuva'),
('Vilkija, Lietuva'),
('Vilnius, Lietuva'),
('Virbalis, Lietuva'),
('Visaginas, Lietuva'),
('Zarasai, Lietuva'),
('Žagarė, Lietuva'),
('Žiežmariai, Lietuva');